#!/bin/sh
# Generates config.js from Vercel environment variables (Build Command: sh build-config.sh).
set -eu

: "${API_BASE_URL:?Set API_BASE_URL in Vercel > Settings > Environment Variables}"
: "${APP_CODE:?Set APP_CODE in Vercel > Settings > Environment Variables}"

cat > config.js <<EOF
// Generated by build-config.sh. Demo only: the AppCode is visible in the browser.
window.APP_CONFIG = {
  API_BASE_URL: "${API_BASE_URL%/}",
  APP_CODE: "${APP_CODE}"
};
EOF

echo "config.js generated"
